[package]
name = "witch_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
ariadne = { version = "0.3.0" }
chumsky = "1.0.0-alpha.4"
hex = "0.4.3"
